=== brickinwall/conup/tags/conup-0.9.0-DU/modules/interface-wsdl/src/test/resources/org/apache/tuscany/sca/interfacedef/wsdl/xml/ipo.xsd
<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
-->
<schema targetNamespace="http://www.example.com/IPO"
	xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:ipo="http://www.example.com/IPO">

	<annotation>
		<documentation xml:lang="en">
			International Purchase order schema for Example.com
			Copyright 2000 Example.com. All rights reserved.
		</documentation>
	</annotation>


	<element name="purchaseOrder" type="ipo:PurchaseOrderType" />

	<element name="comment" type="string" />

	<complexType name="PurchaseOrderType">
		<sequence>
			<element name="shipTo" type="ipo:Address" />
			<element name="billTo" type="ipo:Address" />
			<element ref="ipo:comment" minOccurs="0" />
			<element name="items" type="ipo:Items" />
		</sequence>
		<attribute name="orderDate" type="date" />
	</complexType>

	<complexType name="Items">
		<sequence>
			<element name="item" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="productName" type="string" />
						<element name="quantity">
							<simpleType>
								<restriction base="positiveInteger">
									<maxExclusive value="100" />
								</restriction>
							</simpleType>
						</element>
						<element name="USPrice" type="decimal" />
						<element ref="ipo:comment" minOccurs="0" />
						<element name="shipDate" type="date"
							minOccurs="0" />
					</sequence>
					<attribute name="partNum" type="ipo:SKU"
						use="required" />
				</complexType>
			</element>
		</sequence>
	</complexType>

	<simpleType name="SKU">
		<restriction base="string">
			<pattern value="\d{3}-[A-Z]{2}" />
		</restriction>
	</simpleType>

	<complexType name="Address">
		<sequence>
			<element name="name" type="string" />
			<element name="street" type="string" />
			<element name="city" type="string" />
		</sequence>
	</complexType>

	<complexType name="USAddress">
		<complexContent>
			<extension base="ipo:Address">
				<sequence>
					<element name="state" type="ipo:USState" />
					<element name="zip" type="positiveInteger" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="UKAddress">
		<complexContent>
			<extension base="ipo:Address">
				<sequence>
					<element name="postcode" type="ipo:UKPostcode" />
				</sequence>
				<attribute name="exportCode" type="positiveInteger"
					fixed="1" />
			</extension>
		</complexContent>
	</complexType>

	<!-- other Address derivations for more countries -->

	<simpleType name="USState">
		<restriction base="string">
			<enumeration value="AK" />
			<enumeration value="AL" />
			<enumeration value="AR" />
			<enumeration value="CA" />
			<enumeration value="PA" />
			<!-- and so on ... -->
		</restriction>
	</simpleType>

	<simpleType name="Postcode">
		<restriction base="string">
			<length value="7" fixed="true" />
		</restriction>
	</simpleType>


	<simpleType name="UKPostcode">
		<restriction base="ipo:Postcode">
			<pattern value="[A-Z]{2}\d\s\d[A-Z]{2}" />
		</restriction>
	</simpleType>



</schema>

=== brickinwall/conup/tags/conup-0.9.0-DU/modules/databinding-axiom/src/test/resources/ipo.xml
<?xml version="1.0"?>
<!--
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.    
-->
<ipo:purchaseOrder
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ipo="http://www.example.com/IPO"
  xsi:schemaLocation="http://www.example.com/IPO ipo.xsd"
  orderDate="1999-12-01">

  <shipTo exportCode="1" xsi:type="ipo:UKAddress">
    <name>Helen Zoe</name>
    <street>47 Eden Street</street>
    <city>Cambridge</city>
    <postcode>CB1 1JR</postcode>
  </shipTo>

  <billTo xsi:type="ipo:USAddress">
    <name>Robert Smith</name>
    <street>8 Oak Avenue</street>
    <city>Old Town</city>
    <state>PA</state>
    <zip>95819</zip>
  </billTo>

  <items>
    <item partNum="833-AA">
      <productName>Lapis necklace</productName>
      <quantity>1</quantity>
      <USPrice>99.95</USPrice>
      <ipo:comment>Want this for the holidays</ipo:comment>
      <shipDate>1999-12-05</shipDate>
    </item>
  </items>
</ipo:purchaseOrder>
